#spring:
#  datasource:
#    url: ${JDBC_DATASOURCE_URL}
#    driver-class-name: org.postgresql.Driver
#    username: serqeycheremisin
#    password: sergey90x
#    max-active: 10
#    max-idle: 5
#    min-idle: 2
#    initia-size: 5
#    remove-aboundoned: true

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/lorekeep
    username: serqeycheremisin
    password: sergey90x
    driverClassName: org.postgresql.Driver


#
#database:
#  url: localhost
#  username: serqeycheremisin
#  password: sergey90x
#  name: lorekeep
#  pool: 5
#  showSql: true




#spring.datasource.url= jdbc:postgresql://localhost:5432/springbootdb
#spring.datasource.username=postgres
#spring.datasource.password=postgres@123
#
#spring.jpa.hibernate.ddl-auto=create-drop
#1
#2
#3
#4
#5
#spring.datasource.url= jdbc:postgresql://localhost:5432/springbootdb
#spring.datasource.username=postgres
#spring.datasource.password=postgres@123
#
#spring.jpa.hibernate.ddl-auto=create-drop